set nocompatible

autocmd!
filetype off

let g:vim_root = $HOME."/userpack/dotfiles/vim"
execute "set viminfo='".'20,\"1000,:20,%,n'.vim_root."/viminfo"

"hi Pmenu ctermbg=0
hi PmenuSel ctermbg=4
hi PmenuSbar ctermbg=2
hi PmenuThumb ctermfg=3

if filereadable(expand(vim_root.'/global/all.vim'))
  execute "source ".vim_root."/global/all.vim"
endif

if filereadable(expand(vim_root.'/plugins.vim'))
  execute "source ".vim_root."/plugins.vim"
endif

filetype plugin indent on
syntax on

set background=dark
"colorscheme solarized
