# Set up the prompt

autoload -Uz promptinit
promptinit
prompt walters

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -v

HISTSIZE=100000
SAVEHIST=100000

DOTFILES="${HOME}/dotfiles"
ZSH_ROOT="${DOTFILES}/.shell/zsh"
HISTFILE="${ZSH_ROOT}/history/.zsh_history"

# Use modern completion system
autoload -Uz compinit
compinit -d "${ZSH_ROOT}/.zcompdump"

export LANG=ja_JP.UTF-8

setopt auto_pushd
setopt list_packed
setopt correct

# autoload predict-on
# predict-on

if [ -f "${ZSH_ROOT}/global/completion.zsh" ]; then
    source "${ZSH_ROOT}/global/completion.zsh"
fi

if [ -f "${ZSH_ROOT}/global/history_search.zsh" ]; then
    source "${ZSH_ROOT}/global/history_search.zsh"
fi

if [ -f "${ZSH_ROOT}/global/prompt.zsh" ]; then
    source "${ZSH_ROOT}/global/prompt.zsh"
fi

if [ -f "${DOTFILES}/.shell/alias/aliases" ]; then
    source "${DOTFILES}/.shell/alias/aliases"
fi

if [ -f "${ZSH_ROOT}/global/screen.zsh" ]; then
    source "${ZSH_ROOT}/global/screen.zsh"
fi

if [ -f "${ZSH_ROOT}/local/loadset.zsh" ]; then
    source "${ZSH_ROOT}/local/loadset.zsh"
fi

