# Set up the prompt

autoload -Uz promptinit
promptinit
prompt walters

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -v

bindkey '^[[Z' reverse-menu-complete

HISTSIZE=100000
SAVEHIST=100000

DOTFILES="${HOME}/userpack/dotfiles"
ZSH_ROOT="${DOTFILES}/.shell/zsh"
HISTFILE="${ZSH_ROOT}/history/.zsh_history"

# Use modern completion system
autoload -Uz compinit
compinit -d "${ZSH_ROOT}/.zcompdump"

export LANG=ja_JP.UTF-8

setopt auto_pushd pushdsilent
setopt list_packed

unsetopt correctall

# autoload predict-on
# predict-on

# load bash profile
source /etc/profile

export PATH="$HOME/usr/local/bin:$PATH"
export TERM=xterm-256color

if type "vim" > /dev/null; then
    export EDITOR="vim"
fi

if [ -f "${DOTFILES}/.shell/alias/aliases" ]; then
    source "${DOTFILES}/.shell/alias/aliases"
fi

export EDITOR='vim'

FILES="`\ls ${ZSH_ROOT}/global/*.zsh`"
echo $FILES | while read -r file;
do
    if [ -f "$file" ]; then
        source "$file"
    fi
done

[ ${STY} ] || screen -rx || screen -D -RR

preexec () {
  if [[ $TERMCAP =~ screen ]]; then
    lastcmd=(${(s: :)${1}})
    echo -ne "\ek$lastcmd[1]\e\\"
  fi
}

precmd() {
  if [[ $TERMCAP =~ screen ]]; then
    name=`basename $SHELL`
    echo -ne "\ek$name\e\\"
  fi
}

[ -f ${ZSH_ROOT}/global/zshrc_`uname` ] && source ${ZSH_ROOT}/global/zshrc_`uname`
[ -f ${ZSH_ROOT}/local.zsh ] && ${ZSH_ROOT}/local.zsh

source ${ZSH_ROOT}/global/rbenv.zsh
